name: Test
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
      - name: Copy mocks
        run: |
          cp .github/workflows/mocks/{networking,hardware-configuration}.nix .
          git add networking.nix hardware-configuration.nix
      - name: Build
        run: nix build .#nixosConfigurations.xetex-server.config.system.build.toplevel